# Generated by Django 3.2.9 on 2021-12-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notices',
            name='author',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
