# Generated by Django 3.2.9 on 2021-12-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_notices_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='notices',
            name='slug',
            field=models.CharField(default=0, max_length=130),
            preserve_default=False,
        ),
    ]
